{
 "title": "Traefik Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traefik_service_request_duration_seconds_bucket[1m])) by (le, service))",
     "legendFormat": "{{service}} - p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(traefik_service_request_duration_seconds_bucket[1m])) by (le, service))",
     "legendFormat": "{{service}} - p50"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(traefik_http_requests_total{code=~\"2..\"}[1m])) by (code)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(traefik_http_requests_total{code=~\"4..\"}[1m])) by (code)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(traefik_http_requests_total{code=~\"5..\"}[1m])) by (code)",
     "legendFormat": "5xx"
    }
   ]
  }
 ]
}