version: "3.7"

services:
  traefik:
    image: traefik:2.4.8
    labels:
      # - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)
      # - traefik.http.routers.to-https.entrypoints=http
      # - traefik.http.routers.to-https.middlewares=to-https

      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
      # - traefik.http.routers.traefik.middlewares=auth
      # - traefik.http.routers.traefik.tls=true
      # - traefik.http.routers.traefik.tls.certresolver=letsencrypt

      # - traefik.http.middlewares.to-https.redirectscheme.scheme=https
      # - traefik.http.middlewares.auth.basicauth.users=admin:$2y$10$7UGHP3Ilk0OnRWw4LE/PmeIBJ5ki9QouEClbRsl04eMcNWxWnarca
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      # - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik


networks:
  traefik:
    external: true
