log:
  level: DEBUG

api:
  insecure: true

entryPoints:
  http:
    address: ":80"
  # https:
  #   address: ":443"

providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
    exposedByDefault: false

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
#       httpchallenge:
#         entrypoint: http
#       email: admin@example.com
#       storage: /letsencrypt/acme.json
