global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8082"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
